### ISSUE TITLE
Server jars from 21w41a fail

### ISSUE THREAD

**Issue by StrangeOne101** [LXGaming/Reconstruct#4]
# Description
From 21w41a, "server classes are now signed" according to Mojang. This completely changes the format the jars are in, so the jar cannot be remapped successfully because of this. This only affects server jars and does not affect clients.

To add some more information to this, there is only a single raw class file within the jar now - located at `net/minecraft/bundler/Main.class` (excluding subclasses). The real code is located within the jar at `META-INF/versions/<snapshot>/<snapshot>.jar`. The jar now also contains a `version.json` file which has information about the server jar, including the version, protocol versions, pack versions, release category (so snapshots come under "1.18"), etc.

# Example
```bash
$ java -jar reconstruct-cli-1.3.14.jar -jar minecraft_server_21w43a.jar -mapping mappings_server_21w43a.txt -output remapped_server_21w43a.jar -agree
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
[13:25:29] [Main Thread/INFO]: Reconstruct v1.3.14
[13:25:29] [Main Thread/INFO]: Authors: LX_Gaming
[13:25:29] [Main Thread/INFO]: Source: https://github.com/LXGaming/Reconstruct
[13:25:29] [Main Thread/INFO]: Website: https://lxgaming.github.io/
[13:25:29] [Main Thread/INFO]: Debug mode disabled
[13:25:29] [Main Thread/INFO]: Using 8 threads
[13:25:29] [Main Thread/INFO]: Parsing mappings...
[13:25:38] [Main Thread/INFO]: Mapped:
[13:25:38] [Main Thread/INFO]:  - 5341 Classes
[13:25:38] [Main Thread/INFO]:  - 6155 Constructors
[13:25:38] [Main Thread/INFO]:  - 20467 Fields
[13:25:38] [Main Thread/INFO]:  - 34042 Methods
[13:25:38] [Main Thread/INFO]: Linking...
[13:25:38] [Main Thread/WARN]: Missing net.minecraft.bundler.Main$FileEntry
[13:25:38] [Main Thread/WARN]: Missing net.minecraft.bundler.Main$ResourceParser
[13:25:38] [Main Thread/WARN]: Missing net.minecraft.bundler.Main$Thrower
[13:25:38] [Main Thread/WARN]: Missing net.minecraft.bundler.Main
[13:25:38] [Main Thread/INFO]: Linked 5341 classes
[13:25:38] [Main Thread/INFO]: Transforming...
[13:25:38] [Task Thread #2/ERROR]: Encountered an error while executing io.github.lxgaming.reconstruct.common.task.TransformTask
java.lang.UnsupportedOperationException: Records requires ASM8
        at org.objectweb.asm.ClassVisitor.visit(ClassVisitor.java:112) ~[reconstruct-cli-1.3.14.jar:?]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:569) ~[reconstruct-cli-1.3.14.jar:?]
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[reconstruct-cli-1.3.14.jar:?]
        at io.github.lxgaming.reconstruct.common.task.TransformTask.execute(TransformTask.java:59) ~[reconstruct-cli-1.3.14.jar:?]
        at io.github.lxgaming.common.task.Task.run(Task.java:44) [reconstruct-cli-1.3.14.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[13:25:39] [Main Thread/INFO]: Waiting for TransformTasks to complete...
[13:25:39] [Main Thread/INFO]: Waiting for WriteTask to complete...
[13:25:40] [Shutdown Thread/INFO]: Shutting down...
[13:25:40] [Shutdown Thread/INFO]: Successfully terminated task, continuing with shutdown process...
```

# Solution
Check if the jar contains a `version.json` file, and if it does, extract the classes from the new directory in the new format before continuing like normal

**Comment by LXGaming** [comment]
Thanks for the report, v1.3.15 is available in GitHub Releases

Currently the solution I've implemented is if the Bundler is detected then the inner server jar is extract to disk and that is processed instead.
