### ISSUE TITLE
error in mc 1.18

### ISSUE THREAD

**Issue by FazziCLAY** [LXGaming/Reconstruct#5]
don't pay attention to amethystmc, it just runs net.minecraft.client.main.Main.main(args)
(sorry if I'm writing stupidly, I don't speak English)
```java
C:\_I_PRO\AmethystMC\lib\v1.18>java -Xmx1g -cp "*" ru.fazziclay.amethystmc.Main -accessToken null -version 1.18
Exception in thread "main" java.lang.NoSuchFieldError: a
        at net.minecraft.util.ExtraCodecs$LazyInitializedCodec.toString(SourceFile:348)
        at com.mojang.serialization.Codec.lambda$fieldOf$1(Codec.java:175)
        at com.mojang.serialization.MapCodec$1.toString(MapCodec.java:44)
        at java.base/java.lang.String.valueOf(String.java:4215)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:169)
        at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.toString(RecordCodecBuilder.java:341)
        at java.base/java.lang.String.valueOf(String.java:4215)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:169)
        at com.mojang.serialization.codecs.RecordCodecBuilder$2.toString(RecordCodecBuilder.java:122)
        at com.mojang.serialization.MapCodec$MapCodecCodec.toString(MapCodec.java:101)
        at java.base/java.lang.String.valueOf(String.java:4215)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:169)
        at com.mojang.serialization.codecs.ListCodec.toString(ListCodec.java:82)
        at com.mojang.serialization.Codec.flatXmap(Codec.java:167)
        at net.minecraft.util.ExtraCodecs.nonEmptyList(SourceFile:307)
        at net.minecraft.util.CubicSpline.lambda$codec$5(SourceFile:115)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.util.CubicSpline.codec(SourceFile:113)
        at net.minecraft.world.level.biome.TerrainShaper.<clinit>(SourceFile:28)
        at net.minecraft.world.level.levelgen.NoiseSettings.lambda$static$0(SourceFile:41)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.world.level.levelgen.NoiseSettings.<clinit>(SourceFile:31)
        at net.minecraft.world.level.levelgen.NoiseGeneratorSettings.lambda$static$0(SourceFile:27)
        at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72)
        at net.minecraft.world.level.levelgen.NoiseGeneratorSettings.<clinit>(SourceFile:26)
        at net.minecraft.data.BuiltinRegistries.lambda$static$3(SourceFile:78)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at net.minecraft.data.BuiltinRegistries.<clinit>(SourceFile:77)
        at net.minecraft.core.Registry.<clinit>(SourceFile:269)
        at net.minecraft.server.Bootstrap.bootStrap(SourceFile:49)
        at net.minecraft.client.main.Main.main(SourceFile:153)
        at ru.fazziclay.amethystmc.Main.main(Main.java:41)
```

**Comment by LXGaming** [comment]
Could you please test and confirm that https://github.com/LXGaming/Reconstruct/releases/tag/v1.3.16 works for the Client.
I've only tested this fix with the Server

**Comment by FazziCLAY** [comment]
![image](https://user-images.githubusercontent.com/68351787/144383720-d83af189-b287-4faf-a513-6abc000de617.png)

Excellent! Everything works
tested on mc(client): 1.18; mapping: 1.18 official; reconstruct-cli-1.3.16.jar; java:
```
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

**Comment by FazziCLAY** [comment]
Thank you!
