### ISSUE TITLE
Encountered an error while executing io.github.lxgaming.reconstruct.common.task.TransformTask

### ISSUE THREAD

**Issue by prime89** [LXGaming/Reconstruct#7]
```
[00:24:37] [Task Thread #5/ERROR]: Encountered an error while executing io.github.lxgaming.reconstruct.common.task.TransformTask
java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_271]
	at org.objectweb.asm.signature.SignatureReader.accept(SignatureReader.java:80) ~[reconstruct-cli.jar:?]
	at org.objectweb.asm.commons.Remapper.mapSignature(Remapper.java:211) ~[reconstruct-cli.jar:?]
	at org.objectweb.asm.commons.ClassRemapper.visitMethod(ClassRemapper.java:191) ~[reconstruct-cli.jar:?]
	at org.objectweb.asm.ClassVisitor.visitMethod(ClassVisitor.java:365) ~[reconstruct-cli.jar:?]
	at io.github.lxgaming.reconstruct.common.transformer.rename.ClassVisitorImpl.visitMethod(ClassVisitorImpl.java:33) ~[reconstruct-cli.jar:?]
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1353) ~[reconstruct-cli.jar:?]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:744) ~[reconstruct-cli.jar:?]
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[reconstruct-cli.jar:?]
	at io.github.lxgaming.reconstruct.common.task.TransformTask.execute(TransformTask.java:59) ~[reconstruct-cli.jar:?]
	at io.github.lxgaming.common.task.Task.run(Task.java:44) ~[reconstruct-cli.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_271]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_271]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_271]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_271]
```

![image](https://user-images.githubusercontent.com/8803690/172060611-26899782-887e-4ddb-bb9d-250c63880d75.png)

**Comment by LXGaming** [comment]
Could you please re-test with [Reconstruct v1.3.20](https://github.com/LXGaming/Reconstruct/releases/tag/v1.3.20), I've fixed the exception handling so hopefully the error messages are more helpful.

The RenameTransformer isn't that important so it should now log an error and skip the task instead of exploding.

**Comment by LXGaming** [comment]
Closing due to no response, If this is still an issue I'll reopen.
